### PR TITLE
[DMWCOMM-8] document userInfo Sidebar prop 타입 불일치 수정

### PR DESCRIPTION
**Pull request by ori0o0p**
## Summary
- add ticket implementation plan at `docs/plans/2026-02-14-dmwcomm-8-sidebar-props.md`
- update `Sidebar` prop contract to support fixed mode without requiring interactive props (`setOpenSidebar`, `titleList`)
- guard sidebar behavior by mode (fixed mode hides collapse controls and skips TOC rendering when list is absent)
- related ticket: #51

## Root Cause
- `src/app/(with-header)/document/[id]/userInfo/page.tsx` uses `<Sidebar fixed />`
- `src/components/Sidebar.tsx` previously required interactive-only props, causing TS2739 mismatch

## Verification (2nd Stage)
- `corepack yarn tsc --noEmit`
  - DMWCOMM-8 target error removed (`userInfo/page.tsx` Sidebar prop mismatch no longer appears)
  - remaining failures are pre-existing (`TitleProps.noShow` in division/recent)
- `corepack yarn lint`
  - pre-existing failure: `Failed to load config \"airbnb\"`
- UI verifier agent (Playwright) PASS
  - `/document/1`: collapse/expand and TOC scroll behavior pass
  - `/document/1/userInfo`: fixed sidebar renders without missing-prop regression

## Notes
- This PR is intentionally scoped to DMWCOMM-8 only.
- Follow-up pre-existing tickets:
  - #52 (`TitleProps noShow` mismatch)
  - #53 (`eslint airbnb` config load failure)

### CODE REVIEW

**Comment by ori0o0p** [comment]
3rd verification (PR-level gate) result:\n\n- UI verifier: PASS\n  - strict runtime: worktree , port \n  - : sidebar collapse/expand PASS, TOC click scroll PASS\n  - : fixed sidebar rendering PASS\n- Code verifier:\n  - yarn run v1.22.22
$ /Users/seungwon/.config/superpowers/worktrees/Claudia/dmwcomm-8-sidebar-props/node_modules/.bin/tsc --noEmit
src/app/(with-header)/division/page.tsx(11,11): error TS2322: Type '{ noPadding: true; noShow: true; title: string; group: string; details: string; }' is not assignable to type 'IntrinsicAttributes & TitleProps'.
  Property 'noShow' does not exist on type 'IntrinsicAttributes & TitleProps'.
src/app/(with-header)/division/student/page.tsx(23,28): error TS2322: Type '{ noPadding: true; noShow: true; title: string; group: string; details: string; }' is not assignable to type 'IntrinsicAttributes & TitleProps'.
  Property 'noShow' does not exist on type 'IntrinsicAttributes & TitleProps'.
src/app/(with-header)/recent/page.tsx(18,11): error TS2322: Type '{ noPadding: true; noShow: true; title: string; group: string; details: string; }' is not assignable to type 'IntrinsicAttributes & TitleProps'.
  Property 'noShow' does not exist on type 'IntrinsicAttributes & TitleProps'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.: DMWCOMM-8 target mismatch removed\n  - remaining  failures are pre-existing (tracked by #52)\n  - yarn run v1.22.22
$ next lint
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.: pre-existing airbnb config load failure (tracked by #53)\n  - changed-file diagnostics clean ()\n\nWaiver: applying pre-existing code-verification waiver for lint blocker (#53). No PR-introduced blocking issue detected.

**Comment by ori0o0p** [comment]
3rd verification (PR-level gate) result:

- UI verifier: PASS
  - strict runtime: worktree path used, port 3011
  - /document/1: sidebar collapse/expand PASS, TOC click scroll PASS
  - /document/1/userInfo: fixed sidebar rendering PASS
- Code verifier:
  - corepack yarn tsc --noEmit: DMWCOMM-8 target mismatch removed
  - remaining TitleProps.noShow failures are pre-existing (tracked by #52)
  - corepack yarn lint: pre-existing airbnb config load failure (tracked by #53)
  - changed-file diagnostics clean (src/components/Sidebar.tsx)

Waiver applied: pre-existing code-verification blocker (#53). No PR-introduced blocking issue detected.
